/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Use environment variables in production (Vercel), fallback to hardcoded values in dev
export const projectId = import.meta.env?.VITE_SUPABASE_PROJECT_ID || "vgttzxgulpgxoysogpfs"
export const publicAnonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndHR6eGd1bHBneG95c29ncGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NTA5MzcsImV4cCI6MjA3NjAyNjkzN30.tmvqX0uMaPpWpbUhUkSKXRlkB4KqDkRl9wBZg_a53dA"